### ISSUE TITLE
Support for UHD streams

### ISSUE THREAD

**Issue by sunsettrack4** [rbuehlma/pvr.zattoo#145]
Hello,

Zattoo CH added a package called "Sky Sport", including the UHD channel "Sky Sport Bundesliga UHD". However, it seems that additional parameters are required to get the real UHD stream. Unfortunately, a dummy stream is displayed stating that the device is not supported.

How did you manage to retrieve the correct parameter to get the dolby steams?

Thanks for your support :)

**Comment by rbuehlma** [comment]
I do not have the "Sky Sport" package so I cannot actually analyze it but on the site, it states:
`UHD (only on Apple TV, Fire TV, Android smartphones & tablets and on xBOX)`

Since Kodi (inputstream.adaptive) uses the widevine (DRM system) implementation of a browser (Chrome), and since that implementation does not support the required DRM level, I expect that streaming UHD from Zattoo simply won't work with Kodi or if it does, only on some systems.

**Comment by sunsettrack4** [comment]
There's no DRM on all Sky channels. Furthermore, Dolby isn't supported in Chrome browser as well, but it's running on Kodi.

**Comment by rbuehlma** [comment]
You can try to enable dash_widevine in the settings of the addon if not already done. If that works, we have luck, else there is not much I can do.

**Comment by rbuehlma** [comment]
Closing ticket because of no feedback. Feel free to reopen if there should by any update.
